ci: migrate to docker buildx for building docker image

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -2,23 +2,29 @@ stages:
   - buildImage
 
 variables:
-  GIT_STRATEGY: clone
+  DOCKER_IMAGE_NAME: "tapsellorg/android-sdk"
+  DOCKERHUB_USER: "tapsell"
 
 buildDockerImage:
   stage: buildImage
-  image:
-    name: gcr.io/kaniko-project/executor:debug
-    entrypoint: [ "" ]
-
-  before_script:
-    - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
-
-  script:
-    - imageName="tapsellorg/android-sdk:$CI_COMMIT_TAG"
-    - echo "$imageName"
-    - mv $KANIKO_CONFIG /kaniko/.docker/config.json
-    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $imageName
-  
   only:
-    - master
-    - tags
+    refs:
+      - master
+      - tags
+  image: docker:latest
+  services:
+    - docker:dind
+  before_script:
+    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
+  script:
+    - docker buildx create --use
+    - |
+      if [ "$CI_COMMIT_BRANCH" = "master" ]; then
+        IMAGE_TAG="latest"
+      elif [ -n "$CI_COMMIT_TAG" ]; then
+        IMAGE_TAG="$CI_COMMIT_TAG"
+      else
+        echo "Error: No valid tag found for the image."
+        exit 1
+      fi
+    - docker buildx build --platform linux/amd64 -t "$DOCKER_IMAGE_NAME:$IMAGE_TAG" --push .
